name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.0' # Specify the .NET version you are using

    - name: Restore dependencies
      run: dotnet restore Tests.csproj
      working-directory: ./

    - name: Build
      run: dotnet build Tests.csproj --no-restore --configuration Release
      working-directory: . # Replace 'src' with the directory containing your .csproj or .sln file

    - name: Run tests
      run: dotnet test Tests.csproj --no-build --verbosity normal
      working-directory: . # Replace 'src' with the directory containing your test projects
