name: Run Unity Tests

on:
  push:
    branches:
      - main

jobs:
  unity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Unity License
        run: |
          mkdir -p /tmp/unity
          echo "${{ secrets.UNITY_LICENSE_FILE }}" > /tmp/unity/Unity_lic.ulf

      - name: Run Unity Test Runner
        uses: game-ci/unity-test-runner@v3
        with:
          unityVersion: 2021.3.0f1
          projectPath: .
          testMode: playmode;editmode
          coverageOptions: generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;dontClear
          artifactsPath: artifacts
        env:
          UNITY_LICENSE: /tmp/unity/Unity_lic.ulf
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}



